Add positive test for Mast center detection
Signed-off-by: Dave Thaler <dthaler1968@gmail.com>

diff --git a/.github/workflows/InferenceSystem.yaml b/.github/workflows/InferenceSystem.yaml
--- a/.github/workflows/InferenceSystem.yaml
+++ b/.github/workflows/InferenceSystem.yaml
@@ -117,6 +117,14 @@ jobs:
         type output.log
         findstr /C:"global_prediction: 1" output.log || (echo "Expected global_prediction: 1 not found" && exit /b 1)
 
+    - name: Positive test with MastCenter
+      working-directory: InferenceSystem
+      shell: cmd
+      run: |
+        call .\inference-venv\Scripts\activate.bat && python src/LiveInferenceOrchestrator.py --config ./config/Test/Positive/FastAI_DateRangeHLS_MastCenter.yml --max_iterations 1 > output.log 2>&1
+        type output.log
+        findstr /C:"global_prediction: 1" output.log || (echo "Expected global_prediction: 1 not found" && exit /b 1)
+
     - name: Positive test with NorthSJC
       working-directory: InferenceSystem
       shell: cmd
@@ -142,14 +150,6 @@ jobs:
         findstr /C:"global_prediction: 1" output.log || (echo "Expected global_prediction: 1 not found" && exit /b 1)
 
     # Use negative test cases for other hydrophones where the model has never correctly predicted positive event.
-    - name: Negative test with MastCenter
-      working-directory: InferenceSystem
-      shell: cmd
-      run: |
-        call .\inference-venv\Scripts\activate.bat && python src/LiveInferenceOrchestrator.py --config ./config/Test/Negative/FastAI_DateRangeHLS_MastCenter.yml --max_iterations 1 > output.log 2>&1
-        type output.log
-        findstr /C:"global_prediction: 0" output.log || (echo "Expected global_prediction: 0 not found" && exit /b 1)
-
     - name: Negative test with PointRobinson
       working-directory: InferenceSystem
       shell: cmd
@@ -260,6 +260,13 @@ jobs:
         cat output.log
         grep -q "global_prediction: 1" output.log || (echo "Expected global_prediction: 1 not found" && exit 1)
 
+    - name: Positive test with MastCenter
+      working-directory: InferenceSystem
+      run: |
+        source ./inference-venv/bin/activate && python src/LiveInferenceOrchestrator.py --config ./config/Test/Positive/FastAI_DateRangeHLS_MastCenter.yml --max_iterations 1 > output.log 2>&1
+        cat output.log
+        grep -q "global_prediction: 1" output.log || (echo "Expected global_prediction: 1 not found" && exit 1)
+
     - name: Positive test with NorthSJC
       working-directory: InferenceSystem
       run: |
@@ -280,13 +287,6 @@ jobs:
         source ./inference-venv/bin/activate && python src/LiveInferenceOrchestrator.py --config ./config/Test/Positive/FastAI_DateRangeHLS_SunsetBay.yml --max_iterations 1 > output.log 2>&1
         cat output.log
         grep -q "global_prediction: 1" output.log || (echo "Expected global_prediction: 1 not found" && exit 1)
-
-    - name: Negative test with MastCenter
-      working-directory: InferenceSystem
-      run: |
-        source ./inference-venv/bin/activate && python src/LiveInferenceOrchestrator.py --config ./config/Test/Negative/FastAI_DateRangeHLS_MastCenter.yml --max_iterations 1 > output.log 2>&1
-        cat output.log
-        grep -q "global_prediction: 0" output.log || (echo "Expected global_prediction: 0 not found" && exit 1)
 
     - name: Negative test with PointRobinson
       working-directory: InferenceSystem
