Add positive test case for Andrews Bay
Signed-off-by: Dave Thaler <dthaler1968@gmail.com>

diff --git a/.github/workflows/InferenceSystem.yaml b/.github/workflows/InferenceSystem.yaml
--- a/.github/workflows/InferenceSystem.yaml
+++ b/.github/workflows/InferenceSystem.yaml
@@ -100,6 +100,13 @@ jobs:
         call .\inference-venv\Scripts\activate.bat && python src/LiveInferenceOrchestrator.py --config ./config/Test/Positive/FastAI_DateRangeHLS_OrcasoundLab.yml --max_iterations 2 > output.log 2>&1
         findstr /C:"global_prediction: 1" output.log || (echo "Expected global_prediction: 1 not found" && exit /b 1)
 
+    - name: Positive test with AndrewsBay
+      working-directory: InferenceSystem
+      shell: cmd
+      run: |
+        call .\inference-venv\Scripts\activate.bat && python src/LiveInferenceOrchestrator.py --config ./config/Test/Positive/FastAI_DateRangeHLS_AndrewsBay.yml --max_iterations 1 > output.log 2>&1
+        findstr /C:"global_prediction: 1" output.log || (echo "Expected global_prediction: 1 not found" && exit /b 1)
+
     - name: Positive test with BushPoint
       working-directory: InferenceSystem
       shell: cmd
@@ -123,13 +130,6 @@ jobs:
         findstr /C:"global_prediction: 1" output.log || (echo "Expected global_prediction: 1 not found" && exit /b 1)
 
     # Use negative test cases for other hydrophones where the model has never correctly predicted positive event.
-    - name: Negative test AndrewsBay
-      working-directory: InferenceSystem
-      shell: cmd
-      run: |
-        call .\inference-venv\Scripts\activate.bat && python src/LiveInferenceOrchestrator.py --config ./config/Test/Negative/FastAI_DateRangeHLS_AndrewsBay.yml --max_iterations 1 > output.log 2>&1
-        findstr /C:"global_prediction: 0" output.log || (echo "Expected global_prediction: 0 not found" && exit /b 1)
-
     - name: Negative test with MastCenter
       working-directory: InferenceSystem
       shell: cmd
