Update ubuntu NorthSJC test
Signed-off-by: Dave Thaler <dthaler1968@gmail.com>

diff --git a/.github/workflows/InferenceSystem.yaml b/.github/workflows/InferenceSystem.yaml
--- a/.github/workflows/InferenceSystem.yaml
+++ b/.github/workflows/InferenceSystem.yaml
@@ -260,6 +260,13 @@ jobs:
         cat output.log
         grep -q "global_prediction: 1" output.log || (echo "Expected global_prediction: 1 not found" && exit 1)
 
+    - name: Positive test with NorthSJC
+      working-directory: InferenceSystem
+      run: |
+        source ./inference-venv/bin/activate && python src/LiveInferenceOrchestrator.py --config ./config/Test/Positive/FastAI_DateRangeHLS_NorthSJC.yml --max_iterations 1 > output.log 2>&1
+        cat output.log
+        grep -q "global_prediction: 1" output.log || (echo "Expected global_prediction: 1 not found" && exit 1)
+
     - name: Positive test with PortTownsend
       working-directory: InferenceSystem
       run: |
@@ -278,13 +285,6 @@ jobs:
       working-directory: InferenceSystem
       run: |
         source ./inference-venv/bin/activate && python src/LiveInferenceOrchestrator.py --config ./config/Test/Negative/FastAI_DateRangeHLS_MastCenter.yml --max_iterations 1 > output.log 2>&1
-        cat output.log
-        grep -q "global_prediction: 0" output.log || (echo "Expected global_prediction: 0 not found" && exit 1)
-
-    - name: Negative test with NorthSJC
-      working-directory: InferenceSystem
-      run: |
-        source ./inference-venv/bin/activate && python src/LiveInferenceOrchestrator.py --config ./config/Test/Negative/FastAI_DateRangeHLS_NorthSJC.yml --max_iterations 1 > output.log 2>&1
         cat output.log
         grep -q "global_prediction: 0" output.log || (echo "Expected global_prediction: 0 not found" && exit 1)
 
